### PR TITLE
Update test-containers.yaml

### PR DESCRIPTION
**Pull request by wei-lee**

### CODE REVIEW

**Comment by wei-lee** [comment]
@mikenairn @StevenTobin can you approve the PR? need to try to build the image again to see if the issue is fixed on openshift-ci

**Comment by mikenairn** [comment]
/lgtm

FYI, you can also ask the DPTP team to trigger the postsubmit job for you if needs be, they don't seem to mind.

**Comment by wei-lee** [comment]
@mikenairn thanks. good to know

**Pull request merged**
