### PR TITLE
MGDAPI-4600 update script generation to account for GCP clusters

### PR DESCRIPTION
**Pull request by cecobask**
JIRA: https://issues.redhat.com/browse/MGDAPI-4600

# Verification
## Script that generates cluster configurations
- Non-CCS cluster config:
```
make -f make/ocm.mk ocm/cluster.json
```
- AWS CCS cluster config:
```
make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=aws AWS_ACCOUNT_ID=<> AWS_ACCESS_KEY_ID=<> AWS_SECRET_ACCESS_KEY=<>
```
- GCP CCS cluster config:
```
make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp
```
- GCP CCS BYOVPC cluster config:
```
make -f make/ocm.mk ocm/cluster.json BYOC=true BYOVPC=true CLOUD_PROVIDER=gcp VPC_NAME=<> COMPUTE_SUBNET=<> CONTROL_PLANE_SUBNET=<> MACHINE_CIDR=<> SERVICE_CIDR=<> POD_CIDR=<> HOST_PREFIX=<>
```
## Run cluster/s with generated config (optional)
```
make -f make/ocm.mk ocm/cluster/create
```

### CODE REVIEW

**Comment by valerymo** [comment]
@cecobask , could you please provide more details how to create GCP CCS cluster:
[delorean (MGDAPI-4600)]$ make -f make/ocm.mk ocm/cluster.json BYOC=true CLOUD_PROVIDER=gcp
Error: GCP service account file not found

**Comment by valerymo** [comment]
@cecobask , AWS related errors appear when deleting GCP cluster (annoying). Seems need update delete_cluster() to check PROVIDER. Thank you
https://github.com/integr8ly/delorean/blob/fd3bb9e7b4feac9e8c9dad0aec19ec480f88cefc/scripts/ocm/ocm.sh#L423-L442

**Comment by cecobask** [comment]
@valerymo,

I've addressed the feedback you suggested.
You will need credentials file for GCP. Name it `gcp_service_account.json` and place it in the root of the repository.
Everything should work as expected then 👍🏻

**Comment by valerymo** [comment]
@cecobask   Thank you very much for addressing comments. It looks good for me

**Pull request merged**
