### PR TITLE
add credentials to github call & new confirm-image-origin cmd 

### PR DESCRIPTION
**Pull request by briangallagher**
### What
1. Add credentials to github api call due to hitting rate limiting errors on unauthenticated calls.
2. Add a new command to check for the existence of an image in a repo

### Verify 1
`clone branch`
`make build/cli`
`export GITHUB_TOKEN="<token>"`
`./delorean ews get-latest-release -r ratelimit -o envoyproxy`
**expected output:** v1.4.0

Token can be found here:
https://gitlab.cee.redhat.com/integreatly-qe/ci-cd/-/blob/master/secrets/github-fh-automatron-token

### Verify 2
**success:**
`./delorean ews get-image-origin --imageType "rateLimiting" --imageTag "v1.4.0"`
`Image exists in Repo`

**failure:**
`./delorean ews get-image-origin --imageType "rateLimiting" --imageTag "v1.5.0"`
`Error pulling image:....`

### CODE REVIEW

**Comment by briangallagher** [comment]
@laurafitzgerald Can you do a review?

**Comment by laurafitzgerald** [comment]
👀

**Comment by laurafitzgerald** [comment]
Hey @briangallagher a question as I'm progressing the verification. I chanced putting in another repo for the `-r` value. The help tool says `--repo string    Git repo from which to get latest release version` which made me think we could pass any git repo. I tried sso as I'm aware this is another one we could be interested in. I got the error `Error: Error attempting to get release from github, owner: sso, repo: envoyproxy. Error: GET https://api.github.com/repos/envoyproxy/sso/releases: 404 Not Found []` I think we should either update the help to indicate it's only for envoy repos or allow for other github repos to be entered. wdyt?

**Comment by laurafitzgerald** [comment]
Verification:

Verify 1-> as described. 👍 

Verify 2 -> 
```
./delorean ews get-image-origin --imageType "rateLimiting" --imageTag "v1.4.0"
docker.io/envoyproxy/ratelimit:v1.4.0```
```
./delorean ews get-image-origin --imageType "rateLimiting" --imageTag "v1.5.0"

Error pulling image:  Error response from daemon: manifest for envoyproxy/ratelimit:v1.5.0 not found: manifest unknown: manifest unknown
Error: Error response from daemon: manifest for envoyproxy/ratelimit:v1.5.0 not found: manifest unknown: manifest unknown```

btw, @Boomatang is there any verification steps for your commit?

**Comment by Boomatang** [comment]
@laurafitzgerald Sorry, verification steps. Most of the changes have been covered by the unit test, so run them them should confirm that.
But you will want to check the `verify-image-version` command. You will need the integreatly-operator saved locally (I saved it to /tmp). 
- Complie the delorean cli
- Run `./delorean ews verify-image-version --imageType rhsso --newImage registry-proxy.engineering.redhat.com/rh-osbs/rh-sso-7-sso74-openshift-rhel8:7.4-13 --opDir /tmp/github.com/integr8ly/integreatly-operator`
- Expected result is `New version registry-proxy.engineering.redhat.com/rh-osbs/rh-sso-7-sso74-openshift-rhel8:7.4-13, is a valid update`

**Comment by laurafitzgerald** [comment]
Hi @Boomatang I'm getting the following when I'm doing the verification
```./delorean ews verify-image-version --imageType rhsso --newImage registry-proxy.engineering.redhat.com/rh-osbs/rh-sso-7-sso74-openshift-rhel8:7.4-13 --opDir ~/integreatly/integreatly-operator
Error: Invalid image type rhsso```
The copy of integreatly-operator is master..

**Comment by Boomatang** [comment]
@laurafitzgerald So the cherry-pick for the win didn't work as well as I like. There is on commit in master that is missing on this branch. Do you want me to rebase fully of master or just bring over the commit that is required. Its a one word fix that is in the current master
.

**Comment by laurafitzgerald** [comment]
@Boomatang cheers
verification now is 
```
./delorean ews verify-image-version --imageType rhsso --newImage registry-proxy.engineering.redhat.com/rh-osbs/rh-sso-7-sso74-openshift-rhel8:7.4-13 --opDir ~/integreatly/integreatly-operator
New version registry-proxy.engineering.redhat.com/rh-osbs/rh-sso-7-sso74-openshift-rhel8:7.4-13, is a valid update
```

**Pull request merged**
