### PR TITLE
INTLY-8161 - print 3Scale admin credentials after addon installation

### PR DESCRIPTION
**Pull request by matskiv**
JIRA: https://issues.redhat.com/browse/INTLY-8161

@trepel would you mind reviewing this? I picked you since you recently edited this file :)

### CODE REVIEW

**Comment by trepel** [comment]
Do you have any build log in Jenkins, that would help me validate this ;)

I just tried in terminal localy for now but got following error:
`oc -ns redhat-rhoam-3scale get secret system-seed -o json | jq -r .data.ADMIN_USER | base64 --decode
Error: unknown command "redhat-rhoam-3scale" for "oc"`

However, this worked for me:
`oc -n redhat-rhoam-3scale get secret system-seed -o json | jq -r .data.ADMIN_USER | base64 --decode`

Are you sure with that `-ns` ?

**Comment by matskiv** [comment]
@trepel good catch, i fixed it now.
I will run a pipeline to demonstrate.. if I will be able to use my branch of Delorean in it.. 🤔

**Comment by matskiv** [comment]
@trepel here is pipeline run: 
https://master-jenkins-csb-intly.apps.ocp4.prod.psi.redhat.com/job/ManagedAPI/job/managed-api-install-addon-flow/19/console
After the run I just added a new line between username and password and squashed the commits.

**Comment by trepel** [comment]
It looks much better now!

/lgtm

**Comment by matskiv** [comment]
Thank you for the review @trepel !

@psturc or @laurafitzgerald can you approve this small change please? :)

**Pull request merged**
