### PR TITLE
make sure the right branch image tag is used when create quay image tags

### PR DESCRIPTION
**Pull request by wei-lee**

### CODE REVIEW

**Comment by b1zzu** [comment]
As this util is growing should we maybe evaluate some semver libraries?
* https://github.com/blang/semver
* https://github.com/Masterminds/semver
* https://github.com/coreos/go-semver

**Comment by wei-lee** [comment]
@b1zzu I did think about and looked at it, but seems a bit overkill for what we need at the moment. But if we have more use case (especially around comparing versions), then we should use a module.

**Comment by mikenairn** [comment]
@wei-lee I actually think we should just make it use the branch name in all situations instead of using major.minor, makes it easier to understand, branch in git maps to tag in quay, same for tags in git.

This chnage doesn't prevent us from making that update after though by updating ReleaseBranchImageTag and updateImageMirroringConfig to use the release branch instead.

Current 2.1 config could be updated manually this time round since it's already been created.

**Comment by wei-lee** [comment]
@mikenairn ok, sounds good to me.

**Comment by wei-lee** [comment]
@mikenairn Can you add "/lgtm" to the PR?

**Comment by b1zzu** [comment]
> @b1zzu I did think about and looked at it, but seems a bit overkill for what we need at the moment. But if we have more use case (especially around comparing versions), then we should use a module.

Yes, I agree but is good to keep it in mind if we start to add also version comparison or other semver futures

**Pull request merged**
