### PR TITLE
Update e2e test debug docs

### PR DESCRIPTION
**Pull request by mikenairn**
Update e2e test debug docs to include information about using the e2e-test-extract-creds script and intly operator make targets.

/cc @HubertStefanski

### CODE REVIEW

**Comment by mikenairn** [comment]
/hold

Wait for https://github.com/integr8ly/integreatly-operator/pull/848 to merge since this documents Make targets that won't exist yet.

**Comment by HubertStefanski** [comment]
@mikenairn  I think we're good to unhold, integr8ly/integreatly-operator#848  has been merged

**Comment by mikenairn** [comment]
@HubertStefanski Yep :+1: 

/hold cancel

**Pull request merged**
