### PR TITLE
build our own CSV type based on unstructured type

### PR DESCRIPTION
**Pull request by wei-lee**
See 58cb5eedbba4ce5f0cde576fdae1d68fb37ef4a5

@mikenairn @b1zzu @laurafitzgerald

### CODE REVIEW

**Comment by mikenairn** [comment]
Tried this and the extractManifests seemed to do what we want https://github.com/integr8ly/integreatly-operator/commit/01490a43c855ee9145aa3eef6ab05dbc15892139. Still ordered, but everything is still in the file.

Process manifest didn't work https://github.com/integr8ly/integreatly-operator/commit/e2ba7fa3ab6cfb34d11eaae2adb3e1a79fb4be09, nut maybe not finished yet?

**Comment by wei-lee** [comment]
@mikenairn yes, that issue is fixed now. I have added tests to cover the case.

**Comment by mikenairn** [comment]
Tried it again and worked as expected https://github.com/mikenairn/integreatly-operator/commits/test_crw_update_2.1.1

/lgtm

**Pull request merged**
