### PR TITLE
MGDAPI-509

### PR DESCRIPTION
**Pull request by jjkiely**
# What
Addresses https://issues.redhat.com/browse/MGDAPI-509
# Why
To automatically tag a new osde2e image from osde2e-master when running the release pipeline
# Changes
Nothing was changed other than allowing the Delorean tagRelease function to take in a new parameter "sourceTag" and adding simple logic to tag the correct images with the correct tags
# Verification
I attempted to verify correct tagging of osde2e image using my own quay repo and the Delorean CLI, however I was continually faced with a 403 error, this turned out to be because my repo was under a user and not an organisation and as a result an OAuth token can not be generated for the repo. However, a new test has been added to tagRelease_test.go to ensure proper code execution and coverage. Hopefully full verification can be provided by the next release pipeline.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@jjkiely @Boomatang if you guys are good with this one merging I'll `/approve` it.

**Comment by jjkiely** [comment]
Hey @laurafitzgerald I just want to wait until Michal's PR https://github.com/integr8ly/integreatly-operator/pull/1596 is merged as the changes here are dependent on the work he's done there, thanks :smiley:

**Comment by jjkiely** [comment]
Hey @laurafitzgerald Michal's PR has been merged so I'd be more than happy for you to approve this PR

**Pull request merged**
