### PR TITLE
add cmd to check OLM graph

### PR DESCRIPTION
**Pull request by wei-lee**
https://issues.redhat.com/browse/DEL-345

To verify:

* checkout the branch and build the cli
* run the following command
   ```
   ./delorean ews check-olm-graph -d <manifest dir>
   ```
    You should use the manifest directory in the integreatly-operator (https://github.com/integr8ly/integreatly-operator/tree/master/manifests). The checks should fail because the graph in `integreatly-monitoring` is broken.

### CODE REVIEW

**Comment by mikenairn** [comment]
@wei-lee I'm getting the following error:

```$ ./delorean ews check-olm-graph -d /home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/
Error: no ClusterServiceVersion object found in /home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/integreatly-3scale```

Any idea?

**Comment by wei-lee** [comment]
@mikenairn you need to specify the product manifest directory. So the parameter should be `/home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/integreatly-3scale`

**Comment by wei-lee** [comment]
@mikenairn it could that I misunderstood the requirement here. Does the command should automatically scan all the products in the manifests directory?

**Comment by mikenairn** [comment]
ok i see, this works:

```
$ ./delorean ews check-olm-graph -d /home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/integreatly-3scale/
OLM graph is broken. CSV 3scale-operator.v0.5.4 replaces 3scale-operator.v0.5.3, which doesn't exist
Error: invalid replaces field 3scale-operator.v0.5.3 in CSV 3scale-operator.v0.5.4
```

I guess this will work but we would have to write a test that executed this command in every directory within the manifests dir, which we can do in bash, but kind of thought we'd just do it here to make life easier.

**Comment by wei-lee** [comment]
@mikenairn yeah, we can do it here. I will update the PR.

**Comment by wei-lee** [comment]
@mikenairn fixed now. The check failed for the `integreatly-monitoring` product. I think we should remove [this one](https://github.com/integr8ly/integreatly-operator/tree/master/manifests/integreatly-monitoring/1.1.5) as it shouldn't be there.

**Comment by mikenairn** [comment]
Works as expected:

```
$ ./delorean ews check-olm-graph -d /home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/
[integreatly-amq-streams] no graph to check
[integreatly-apicurito] OLM graph is complete
[integreatly-cloud-resources] OLM graph is complete
[integreatly-3scale] OLM graph is complete
[integreatly-codeready-workspaces] OLM graph is complete
[integreatly-fuse-online] no graph to check
[integreatly-monitoring] OLM graph is broken. CSV application-monitoring-operator.v1.2.1 replaces , which doesn't exist
[integreatly-rhsso] OLM graph is complete
[integreatly-solution-explorer] OLM graph is complete
[integreatly-unifiedpush] no graph to check
[integreatly-amq-online] OLM graph is complete
Error: OLM graph check failed in /home/mnairn/go/src/github.com/integr8ly/integreatly-operator/manifests/

$ echo $?
1
```

**Pull request merged**
