### PR TITLE
doc: add note in cluster creation doc on multiple azs

### PR DESCRIPTION
**Pull request by darahayes**
Ping @psturc just some docs change to go along with your recent changes in #140

### CODE REVIEW

**Comment by darahayes** [comment]
My plan is to then create a doc in the `integreatly-operator` repo that points to this doc for cluster creation and then documents how to install managed-api on top of it.

**Comment by psturc** [comment]
thanks @darahayes, that's great, I'm always forgetting about documentation :)

> My plan is to then create a doc in the `integreatly-operator` repo that points to this doc for cluster creation and then documents how to install managed-api on top of it.

would it also make sense to modify [this doc](https://github.com/RHCloudServices/integreatly-help/blob/master/guides/ocp4/osd_dev_cluster.md) in the integreatly-help repo?

/lgtm
/approve

**Comment by darahayes** [comment]
@psturc to me that doc you linked in the integreatly-help repo almost looks like a duplicate of the one here. Would it make sense to maybe remove the steps in there (creating cluster definition files) and just linking to this doc? In any case, both docs are only about getting a cluster and do not mention actually installing integreatly/managed-api/whatever. I think for actual managed-api/rhmi installation, we should probably document that in the integreatly-operator repo.

**Comment by psturc** [comment]
@darahayes it makes sense to me to add a link for `docs/ocm/README.md` to the doc in integreatly-help repo, instead of documenting the same thing there.

The guide in this repo actually mentions the installation of RHMI via **addon**, but adding a guide for managed-api/rhmi installation (from master branch) to integreatly-operator repo seems reasonable to me. If you're going to create that guide, I think it would be good to also add a link to it to `docs/ocm/README.md` as well.

**Pull request merged**
