### PR TITLE
Nightly reports

### PR DESCRIPTION
**Pull request by pawelpaszki**
## What
moved nightly reports generating file from integreatly-operator repo

### CODE REVIEW

**Comment by pawelpaszki** [comment]
ping @mikenairn @psturc

**Comment by pawelpaszki** [comment]
Generated report:

```

Nightly pipelines results for week ending at 2020-06-03

Pipeline: rhmi-install-addon-flow


	#93	2020-06-02	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-addon-flow/93/
		Note: Stage 'Run the test suite' has failed

	#92	2020-06-01	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-addon-flow/92/
		Note: Stage 'Run the test suite' has failed

	#91	2020-05-31	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-addon-flow/91/
		Note: Stage 'Run the test suite' has failed
ERROR: Failed to delete RHMI CR (uninstallation)

	#90	2020-05-28	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-addon-flow/90/
		Note: Stage 'Install RHMI using Addon-flow' has failed

	#89	2020-05-27	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-addon-flow/89/
Pipeline: rhmi-install-master


	#92	2020-06-03	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/92/

	#91	2020-06-02	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/91/

	#90	2020-06-01	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/90/
		Note: Stage 'Run the test suite' has failed
ERROR: Failed to delete RHMI CR (uninstallation)

	#89	2020-05-29	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/89/
		Note: Stage 'Install RHMI from master' has failed

	#88	2020-05-28	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-install-master/88/
		Note: Stage 'Run the test suite' has failed
Pipeline: rhmi-openshift-upgrade


	#71	2020-06-03	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-openshift-upgrade/71/
		Note: Stage 'Run the test suite (post-upgrade)' has failed

	#70	2020-06-02	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-openshift-upgrade/70/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
Stage 'Run the test suite (post-upgrade)' has failed

	#69	2020-06-01	Result: ABORTED	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-openshift-upgrade/69/
		Note: Stage 'Run the test suite (post-upgrade)' has failed

	#68	2020-05-29	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-openshift-upgrade/68/
		Note: Stage 'Install RHMI from master' has failed

	#67	2020-05-28	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-openshift-upgrade/67/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
Stage 'Run the test suite (post-upgrade)' has failed
Pipeline: rhmi-upgrade


	#40	2020-06-03	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-upgrade/40/

	#39	2020-06-02	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-upgrade/39/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
Stage 'Run the test suite (post-upgrade)' has failed

	#38	2020-06-01	Result: UNSTABLE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-upgrade/38/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
Stage 'Run the test suite (post-upgrade)' has failed

	#37	2020-05-29	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-upgrade/37/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
Stage 'Run the test suite (post-upgrade)' has failed

	#36	2020-05-28	Result: FAILURE	Url: https://master-jenkins-csb-intly.cloud.paas.psi.redhat.com/job/Nightly/job/rhmi-upgrade/36/
		Note: Stage 'Run the test suite (pre-upgrade)' has failed
```

**Comment by psturc** [comment]
LGTM. So now we're able to run the nightly report script from the delorean image?

If so, we could change the way we're running the reporting script - i.e. instead of cloning the repo, we can run the delorean image.

Also we can do the same for ocm.

/lgtm

**Comment by pawelpaszki** [comment]
@psturc - that's the plan. I will change the pipeline after this is merged

**Comment by mikenairn** [comment]
/lgtm

@pawelpaszki Do you want to add an owners file in that directory so you can make changes to the script without needing approval from delorean team members. (scripts/jenkins-reports/OWNERS),. Add yourself and @psturc maybe

**Comment by pawelpaszki** [comment]
@psturc - added owners. Can you please approve and lgtm again?

**Comment by psturc** [comment]
I think `approve` won't work this time, but let's try it anyway:
/lgtm
/approve

**Pull request merged**
