### PR TITLE
Add openshift ci add branch command

### PR DESCRIPTION
**Pull request by mikenairn**
Add openshift ci add branch command to allow adding config for any given branch and not just a release.

```
./delorean openshift-ci add-branch --branch 3scale-next-0.6.1 --repo-dir /home/mnairn/src/openshift/release
```

### CODE REVIEW

**Comment by psturc** [comment]
/lgtm

Verified with `3scale-next-0.7.0` branch: https://github.com/openshift/release/pull/12936

@mikenairn anything else that needs to be added to this PR?

**Comment by mikenairn** [comment]
It can be merged tbh, i doubt anyone is going to be able to have to do much else with it at the moment, and it is handy for generating those EWS branch configs.

/retitle Add openshift ci add branch command

**Pull request merged**
