### PR TITLE
add a new merge-blocker command to create or close merge blockers

### PR DESCRIPTION
**Pull request by wei-lee**
https://issues.redhat.com/browse/DEL-233.

You should review this commit: https://github.com/integr8ly/delorean/pull/12/commits/651591ded05e79d288d86ca7276e775b6b741dbf

To verify:

```
make build/cli
./delorean merge-blocker
# you should see a github issue created
./delorean merge-blocker -d
# you should see the issue is closed
```

### CODE REVIEW

**Comment by mikenairn** [comment]
Ran through the following and all worked as expected:

```
$ ./delorean merge-blocker -b delorean-ews
Merge blocker issue created: https://api.github.com/repos/integr8ly/integreatly-operator/issues/583
$ ./delorean merge-blocker -b delorean-ews
Merge blocker issue is already created: https://api.github.com/repos/integr8ly/integreatly-operator/issues/583
```
Screenshot from 2020-04-06 13-43-35
```
$ ./delorean merge-blocker --delete -b delorean-ews
Merge blocker issue closed: https://api.github.com/repos/integr8ly/integreatly-operator/issues/583
```
Screenshot from 2020-04-06 13-46-34

**Comment by mikenairn** [comment]
Couple of comments, but all worked as expected.

/lgtm

**Comment by wei-lee** [comment]
@mikenairn all comments addressed. See 977607b54b3a5e89c5d578e47c27964522783d8f.

**Pull request merged**
